### ISSUE TITLE
Assigning members on possibly invalid `AL.currentCtx` on `getGlobalHelper()` and others

### ISSUE THREAD

**Issue by yoanlcq** [jpernst/emscripten#3]
In some functions such as `getGlobalHelper`,
```javascript
getGlobalHelper: function(funcname, param) {
    if (!AL.currentCtx) {
        // ...
        AL.currentCtx.err = 0xA004 /* AL_INVALID_OPERATION */;
        return null;
    }
    // ...
```
There's an assignment to `AL.currentCtx.err` even though `AL.currentCtx` is null or something.  
Was that intended?

**Comment by jpernst** [comment]
Woops, good catch. Probably a copy-paste problem. Removed those.
