### ISSUE TITLE
Tracking issue for documentation

### ISSUE THREAD

**Issue by yoanlcq** [jpernst/emscripten#6]
Creating this so we don't forget to keep the doc in sync with our implementation, and have a place to discuss it (feel free to close if it's annoying).

Currently I've mostly documented the capture implementation for external users. Some information I've put (especially supported extensions) may be erroneous, and we might want to also mention "interesting" implementation details of everything not related to capture.

**Comment by jpernst** [comment]
Good call, there are a few deviations from the spec that I should probably add to that.

**Comment by yoanlcq** [comment]
(Felt like cleaning up my issues list today, and since this one isn't relevant anymore because we would get feedback from the PR instead, I'm closing this. Feel free to reopen.)
